// Code generated by values-schema-gen; DO NOT EDIT.

package apis

import (
	"k8s.io/api/core/v1"
)

func (a *ArchConfig) GetAmd64() int {
	if a == nil || a.Amd64 == nil {
		return 0
	}
	return *a.Amd64
}

func (a *ArchConfig) GetPpc64le() int {
	if a == nil || a.Ppc64le == nil {
		return 0
	}
	return *a.Ppc64le
}

func (a *ArchConfig) GetS390x() int {
	if a == nil || a.S390x == nil {
		return 0
	}
	return *a.S390x
}

func (a *ArchConfig) GetArm64() int {
	if a == nil || a.Arm64 == nil {
		return 0
	}
	return *a.Arm64
}

func (d *DefaultPodDisruptionBudgetConfig) GetEnabled() bool {
	if d == nil || d.Enabled == nil {
		return false
	}
	return *d.Enabled
}

func (d *DefaultResourcesConfig) GetRequests() *ResourcesRequestsConfig {
	if d == nil {
		return nil
	}
	return d.Requests
}

func (g *GlobalLoggingConfig) GetLevel() string {
	if g == nil {
		return ""
	}
	return g.Level
}

func (g *GlobalValues) GetArch() *ArchConfig {
	if g == nil {
		return nil
	}
	return g.Arch
}

func (g *GlobalValues) GetCaAddress() string {
	if g == nil {
		return ""
	}
	return g.CaAddress
}

func (g *GlobalValues) GetCaName() string {
	if g == nil {
		return ""
	}
	return g.CaName
}

func (g *GlobalValues) GetCertSigners() []string {
	if g == nil {
		return nil
	}
	return g.CertSigners
}

func (g *GlobalValues) GetConfigCluster() bool {
	if g == nil || g.ConfigCluster == nil {
		return false
	}
	return *g.ConfigCluster
}

func (g *GlobalValues) GetConfigValidation() bool {
	if g == nil || g.ConfigValidation == nil {
		return false
	}
	return *g.ConfigValidation
}

func (g *GlobalValues) GetDefaultNodeSelector() map[string]string {
	if g == nil {
		return nil
	}
	return g.DefaultNodeSelector
}

func (g *GlobalValues) GetDefaultPodDisruptionBudget() *DefaultPodDisruptionBudgetConfig {
	if g == nil {
		return nil
	}
	return g.DefaultPodDisruptionBudget
}

func (g *GlobalValues) GetDefaultResources() *DefaultResourcesConfig {
	if g == nil {
		return nil
	}
	return g.DefaultResources
}

func (g *GlobalValues) GetDefaultTolerations() []v1.Toleration {
	if g == nil {
		return nil
	}
	return g.DefaultTolerations
}

func (g *GlobalValues) GetExternalIstiod() bool {
	if g == nil || g.ExternalIstiod == nil {
		return false
	}
	return *g.ExternalIstiod
}

func (g *GlobalValues) GetHub() string {
	if g == nil {
		return ""
	}
	return g.Hub
}

func (g *GlobalValues) GetImagePullPolicy() ImagePullPolicy {
	if g == nil {
		return ""
	}
	return g.ImagePullPolicy
}

func (g *GlobalValues) GetImagePullSecrets() []string {
	if g == nil {
		return nil
	}
	return g.ImagePullSecrets
}

func (g *GlobalValues) GetIstioNamespace() string {
	if g == nil {
		return ""
	}
	return g.IstioNamespace
}

func (g *GlobalValues) GetIstiod() *IstiodConfig {
	if g == nil {
		return nil
	}
	return g.Istiod
}

func (g *GlobalValues) GetLogAsJson() bool {
	if g == nil || g.LogAsJson == nil {
		return false
	}
	return *g.LogAsJson
}

func (g *GlobalValues) GetLogging() *GlobalLoggingConfig {
	if g == nil {
		return nil
	}
	return g.Logging
}

func (g *GlobalValues) GetMeshID() string {
	if g == nil {
		return ""
	}
	return g.MeshID
}

func (g *GlobalValues) GetMeshNetworks() map[string]any {
	if g == nil {
		return nil
	}
	return g.MeshNetworks
}

func (g *GlobalValues) GetMountMtlsCerts() bool {
	if g == nil || g.MountMtlsCerts == nil {
		return false
	}
	return *g.MountMtlsCerts
}

func (g *GlobalValues) GetMultiCluster() *MultiClusterConfig {
	if g == nil {
		return nil
	}
	return g.MultiCluster
}

func (g *GlobalValues) GetNativeNftables() bool {
	if g == nil || g.NativeNftables == nil {
		return false
	}
	return *g.NativeNftables
}

func (g *GlobalValues) GetNetwork() string {
	if g == nil {
		return ""
	}
	return g.Network
}

func (g *GlobalValues) GetNetworkPolicy() *NetworkPolicyConfig {
	if g == nil {
		return nil
	}
	return g.NetworkPolicy
}

func (g *GlobalValues) GetOmitSidecarInjectorConfigMap() bool {
	if g == nil || g.OmitSidecarInjectorConfigMap == nil {
		return false
	}
	return *g.OmitSidecarInjectorConfigMap
}

func (g *GlobalValues) GetOperatorManageWebhooks() bool {
	if g == nil || g.OperatorManageWebhooks == nil {
		return false
	}
	return *g.OperatorManageWebhooks
}

func (g *GlobalValues) GetPilotCertProvider() string {
	if g == nil {
		return ""
	}
	return g.PilotCertProvider
}

func (g *GlobalValues) GetPriorityClassName() string {
	if g == nil {
		return ""
	}
	return g.PriorityClassName
}

func (g *GlobalValues) GetProxy() *ProxyConfig {
	if g == nil {
		return nil
	}
	return g.Proxy
}

func (g *GlobalValues) GetProxyInit() *ProxyInitConfig {
	if g == nil {
		return nil
	}
	return g.ProxyInit
}

func (g *GlobalValues) GetRemotePilotAddress() string {
	if g == nil {
		return ""
	}
	return g.RemotePilotAddress
}

func (g *GlobalValues) GetResourceScope() ResourceScope {
	if g == nil {
		return ""
	}
	return g.ResourceScope
}

func (g *GlobalValues) GetSds() *SDSConfig {
	if g == nil {
		return nil
	}
	return g.Sds
}

func (g *GlobalValues) GetSts() *STSConfig {
	if g == nil {
		return nil
	}
	return g.Sts
}

func (g *GlobalValues) GetTag() any {
	if g == nil {
		return nil
	}
	return g.Tag
}

func (g *GlobalValues) GetVariant() string {
	if g == nil {
		return ""
	}
	return g.Variant
}

func (g *GlobalValues) GetWaypoint() *WaypointConfig {
	if g == nil {
		return nil
	}
	return g.Waypoint
}

func (i *IstiodConfig) GetEnableAnalysis() bool {
	if i == nil || i.EnableAnalysis == nil {
		return false
	}
	return *i.EnableAnalysis
}

func (m *MultiClusterConfig) GetEnabled() bool {
	if m == nil || m.Enabled == nil {
		return false
	}
	return *m.Enabled
}

func (m *MultiClusterConfig) GetClusterName() string {
	if m == nil {
		return ""
	}
	return m.ClusterName
}

func (m *MultiClusterConfig) GetGlobalDomainSuffix() string {
	if m == nil {
		return ""
	}
	return m.GlobalDomainSuffix
}

func (m *MultiClusterConfig) GetIncludeEnvoyFilter() bool {
	if m == nil || m.IncludeEnvoyFilter == nil {
		return false
	}
	return *m.IncludeEnvoyFilter
}

func (n *NetworkPolicyConfig) GetEnabled() bool {
	if n == nil || n.Enabled == nil {
		return false
	}
	return *n.Enabled
}

func (p *ProxyConfig) GetAutoInject() string {
	if p == nil {
		return ""
	}
	return p.AutoInject
}

func (p *ProxyConfig) GetClusterDomain() string {
	if p == nil {
		return ""
	}
	return p.ClusterDomain
}

func (p *ProxyConfig) GetComponentLogLevel() string {
	if p == nil {
		return ""
	}
	return p.ComponentLogLevel
}

func (p *ProxyConfig) GetEnableCoreDump() bool {
	if p == nil || p.EnableCoreDump == nil {
		return false
	}
	return *p.EnableCoreDump
}

func (p *ProxyConfig) GetExcludeInboundPorts() string {
	if p == nil {
		return ""
	}
	return p.ExcludeInboundPorts
}

func (p *ProxyConfig) GetExcludeIPRanges() string {
	if p == nil {
		return ""
	}
	return p.ExcludeIPRanges
}

func (p *ProxyConfig) GetExcludeOutboundPorts() string {
	if p == nil {
		return ""
	}
	return p.ExcludeOutboundPorts
}

func (p *ProxyConfig) GetImage() string {
	if p == nil {
		return ""
	}
	return p.Image
}

func (p *ProxyConfig) GetIncludeIPRanges() string {
	if p == nil {
		return ""
	}
	return p.IncludeIPRanges
}

func (p *ProxyConfig) GetIncludeInboundPorts() string {
	if p == nil {
		return ""
	}
	return p.IncludeInboundPorts
}

func (p *ProxyConfig) GetIncludeOutboundPorts() string {
	if p == nil {
		return ""
	}
	return p.IncludeOutboundPorts
}

func (p *ProxyConfig) GetLifecycle() *v1.Lifecycle {
	if p == nil {
		return nil
	}
	return p.Lifecycle
}

func (p *ProxyConfig) GetLogLevel() string {
	if p == nil {
		return ""
	}
	return p.LogLevel
}

func (p *ProxyConfig) GetOutlierLogPath() string {
	if p == nil {
		return ""
	}
	return p.OutlierLogPath
}

func (p *ProxyConfig) GetPrivileged() bool {
	if p == nil || p.Privileged == nil {
		return false
	}
	return *p.Privileged
}

func (p *ProxyConfig) GetReadinessInitialDelaySeconds() int {
	if p == nil {
		return 0
	}
	return p.ReadinessInitialDelaySeconds
}

func (p *ProxyConfig) GetReadinessPeriodSeconds() int {
	if p == nil {
		return 0
	}
	return p.ReadinessPeriodSeconds
}

func (p *ProxyConfig) GetReadinessFailureThreshold() int {
	if p == nil {
		return 0
	}
	return p.ReadinessFailureThreshold
}

func (p *ProxyConfig) GetResources() *Resources {
	if p == nil {
		return nil
	}
	return p.Resources
}

func (p *ProxyConfig) GetSeccompProfile() *v1.SeccompProfile {
	if p == nil {
		return nil
	}
	return p.SeccompProfile
}

func (p *ProxyConfig) GetStartupProbe() *StartupProbe {
	if p == nil {
		return nil
	}
	return p.StartupProbe
}

func (p *ProxyConfig) GetStatusPort() int {
	if p == nil {
		return 0
	}
	return p.StatusPort
}

func (p *ProxyConfig) GetTracer() string {
	if p == nil {
		return ""
	}
	return p.Tracer
}

func (p *ProxyConfig) GetHoldApplicationUntilProxyStarts() bool {
	if p == nil || p.HoldApplicationUntilProxyStarts == nil {
		return false
	}
	return *p.HoldApplicationUntilProxyStarts
}

func (p *ProxyInitConfig) GetImage() string {
	if p == nil {
		return ""
	}
	return p.Image
}

func (p *ProxyInitConfig) GetResources() *Resources {
	if p == nil {
		return nil
	}
	return p.Resources
}

func (p *ProxyInitConfig) GetForceApplyIptables() bool {
	if p == nil || p.ForceApplyIptables == nil {
		return false
	}
	return *p.ForceApplyIptables
}

func (r *Resources) GetLimits() map[string]string {
	if r == nil {
		return nil
	}
	return r.Limits
}

func (r *Resources) GetRequests() map[string]string {
	if r == nil {
		return nil
	}
	return r.Requests
}

func (r *ResourcesRequestsConfig) GetCpu() string {
	if r == nil {
		return ""
	}
	return r.Cpu
}

func (r *ResourcesRequestsConfig) GetMemory() string {
	if r == nil {
		return ""
	}
	return r.Memory
}

func (s *SDSConfig) GetToken() map[string]any {
	if s == nil {
		return nil
	}
	return s.Token
}

func (s *STSConfig) GetServicePort() int {
	if s == nil {
		return 0
	}
	return s.ServicePort
}

func (s *StartupProbe) GetEnabled() bool {
	if s == nil || s.Enabled == nil {
		return false
	}
	return *s.Enabled
}

func (s *StartupProbe) GetFailureThreshold() int {
	if s == nil {
		return 0
	}
	return s.FailureThreshold
}

func (w *WaypointConfig) GetResources() *Resources {
	if w == nil {
		return nil
	}
	return w.Resources
}

func (w *WaypointConfig) GetAffinity() *v1.Affinity {
	if w == nil {
		return nil
	}
	return w.Affinity
}

func (w *WaypointConfig) GetTopologySpreadConstraints() []v1.TopologySpreadConstraint {
	if w == nil {
		return nil
	}
	return w.TopologySpreadConstraints
}

func (w *WaypointConfig) GetNodeSelector() map[string]string {
	if w == nil {
		return nil
	}
	return w.NodeSelector
}

func (w *WaypointConfig) GetToleration() []v1.Toleration {
	if w == nil {
		return nil
	}
	return w.Toleration
}

func (v *Values) GetCni() *CniValues {
	if v == nil {
		return nil
	}
	return v.Cni
}

func (v *Values) GetGateways() *GatewaysConfig {
	if v == nil {
		return nil
	}
	return v.Gateways
}

func (v *Values) GetGlobal() *GlobalValues {
	if v == nil {
		return nil
	}
	return v.Global
}

func (v *Values) GetPilot() *DiscoveryValues {
	if v == nil {
		return nil
	}
	return v.Pilot
}

func (v *Values) GetZtunnel() *ZtunnelValues {
	if v == nil {
		return nil
	}
	return v.Ztunnel
}

func (v *Values) GetTelemetry() *ValuesTelemetry {
	if v == nil {
		return nil
	}
	return v.Telemetry
}

func (v *Values) GetSidecarInjectorWebhook() *SidecarInjectorConfig {
	if v == nil {
		return nil
	}
	return v.SidecarInjectorWebhook
}

func (v *Values) GetIstioCni() *CNIUsageConfig {
	if v == nil {
		return nil
	}
	return v.IstioCni
}

func (v *Values) GetRevision() string {
	if v == nil {
		return ""
	}
	return v.Revision
}

func (v *Values) GetOwnerName() string {
	if v == nil {
		return ""
	}
	return v.OwnerName
}

func (v *Values) GetMeshConfig() any {
	if v == nil {
		return nil
	}
	return v.MeshConfig
}

func (v *Values) GetBase() *BaseConfig {
	if v == nil {
		return nil
	}
	return v.Base
}

func (v *Values) GetIstiodRemote() *IstiodRemoteConfig {
	if v == nil {
		return nil
	}
	return v.IstiodRemote
}

func (v *Values) GetRevisionTags() []string {
	if v == nil {
		return nil
	}
	return v.RevisionTags
}

func (v *Values) GetDefaultRevision() string {
	if v == nil {
		return ""
	}
	return v.DefaultRevision
}

func (v *Values) GetProfile() string {
	if v == nil {
		return ""
	}
	return v.Profile
}

func (v *Values) GetCompatibilityVersion() string {
	if v == nil {
		return ""
	}
	return v.CompatibilityVersion
}

func (v *Values) GetExperimental() *ValuesExperimental {
	if v == nil {
		return nil
	}
	return v.Experimental
}

func (v *Values) GetGatewayClasses() any {
	if v == nil {
		return nil
	}
	return v.GatewayClasses
}

func (b *BaseConfig) GetEnableCRDTemplates() bool {
	if b == nil || b.EnableCRDTemplates == nil {
		return false
	}
	return *b.EnableCRDTemplates
}

func (b *BaseConfig) GetExcludedCRDs() []string {
	if b == nil {
		return nil
	}
	return b.ExcludedCRDs
}

func (b *BaseConfig) GetValidationURL() string {
	if b == nil {
		return ""
	}
	return b.ValidationURL
}

func (b *BaseConfig) GetEnableIstioConfigCRDs() bool {
	if b == nil || b.EnableIstioConfigCRDs == nil {
		return false
	}
	return *b.EnableIstioConfigCRDs
}

func (b *BaseConfig) GetValidateGateway() bool {
	if b == nil || b.ValidateGateway == nil {
		return false
	}
	return *b.ValidateGateway
}

func (b *BaseConfig) GetValidationCABundle() string {
	if b == nil {
		return ""
	}
	return b.ValidationCABundle
}

func (c *CNIUsageConfig) GetEnabled() bool {
	if c == nil || c.Enabled == nil {
		return false
	}
	return *c.Enabled
}

func (c *CNIUsageConfig) GetChained() bool {
	if c == nil || c.Chained == nil {
		return false
	}
	return *c.Chained
}

func (c *CNIUsageConfig) GetProvider() string {
	if c == nil {
		return ""
	}
	return c.Provider
}

func (d *DiscoveryValues) GetInternalDefaultsDoNotSet() map[string]any {
	if d == nil {
		return nil
	}
	return d.InternalDefaultsDoNotSet
}

func (d *DiscoveryValues) GetAffinity() *v1.Affinity {
	if d == nil {
		return nil
	}
	return d.Affinity
}

func (d *DiscoveryValues) GetAutoscaleBehavior() map[string]any {
	if d == nil {
		return nil
	}
	return d.AutoscaleBehavior
}

func (d *DiscoveryValues) GetAutoscaleEnabled() bool {
	if d == nil || d.AutoscaleEnabled == nil {
		return false
	}
	return *d.AutoscaleEnabled
}

func (d *DiscoveryValues) GetAutoscaleMax() int {
	if d == nil || d.AutoscaleMax == nil {
		return 0
	}
	return *d.AutoscaleMax
}

func (d *DiscoveryValues) GetAutoscaleMin() int {
	if d == nil || d.AutoscaleMin == nil {
		return 0
	}
	return *d.AutoscaleMin
}

func (d *DiscoveryValues) GetBase() *DiscoveryValuesBase {
	if d == nil {
		return nil
	}
	return d.Base
}

func (d *DiscoveryValues) GetCni() *DiscoveryValuesCni {
	if d == nil {
		return nil
	}
	return d.Cni
}

func (d *DiscoveryValues) GetCompatibilityVersion() string {
	if d == nil || d.CompatibilityVersion == nil {
		return ""
	}
	return *d.CompatibilityVersion
}

func (d *DiscoveryValues) GetConfigMap() bool {
	if d == nil || d.ConfigMap == nil {
		return false
	}
	return *d.ConfigMap
}

func (d *DiscoveryValues) GetCpu() *DiscoveryValuesCpu {
	if d == nil {
		return nil
	}
	return d.Cpu
}

func (d *DiscoveryValues) GetDefaultRevision() string {
	if d == nil || d.DefaultRevision == nil {
		return ""
	}
	return *d.DefaultRevision
}

func (d *DiscoveryValues) GetDeploymentAnnotations() map[string]string {
	if d == nil {
		return nil
	}
	return d.DeploymentAnnotations
}

func (d *DiscoveryValues) GetDeploymentLabels() map[string]string {
	if d == nil {
		return nil
	}
	return d.DeploymentLabels
}

func (d *DiscoveryValues) GetEnv() map[string]string {
	if d == nil {
		return nil
	}
	return d.Env
}

func (d *DiscoveryValues) GetEnvVarFrom() []DiscoveryValuesEnvVarFromElem {
	if d == nil {
		return nil
	}
	return d.EnvVarFrom
}

func (d *DiscoveryValues) GetExperimental() *ValuesExperimental {
	if d == nil {
		return nil
	}
	return d.Experimental
}

func (d *DiscoveryValues) GetExtraContainerArgs() []string {
	if d == nil {
		return nil
	}
	return d.ExtraContainerArgs
}

func (d *DiscoveryValues) GetGatewayClasses() map[string]any {
	if d == nil {
		return nil
	}
	return d.GatewayClasses
}

func (d *DiscoveryValues) GetGateways() *DiscoveryValuesGateways {
	if d == nil {
		return nil
	}
	return d.Gateways
}

func (d *DiscoveryValues) GetGlobal() *GlobalValues {
	if d == nil {
		return nil
	}
	return d.Global
}

func (d *DiscoveryValues) GetHub() string {
	if d == nil || d.Hub == nil {
		return ""
	}
	return *d.Hub
}

func (d *DiscoveryValues) GetImage() string {
	if d == nil || d.Image == nil {
		return ""
	}
	return *d.Image
}

func (d *DiscoveryValues) GetInitContainers() []v1.Container {
	if d == nil {
		return nil
	}
	return d.InitContainers
}

func (d *DiscoveryValues) GetIpFamilies() []string {
	if d == nil {
		return nil
	}
	return d.IpFamilies
}

func (d *DiscoveryValues) GetIpFamilyPolicy() string {
	if d == nil || d.IpFamilyPolicy == nil {
		return ""
	}
	return *d.IpFamilyPolicy
}

func (d *DiscoveryValues) GetIstiodRemote() *DiscoveryValuesIstiodRemote {
	if d == nil {
		return nil
	}
	return d.IstiodRemote
}

func (d *DiscoveryValues) GetJwksResolverExtraRootCA() string {
	if d == nil || d.JwksResolverExtraRootCA == nil {
		return ""
	}
	return *d.JwksResolverExtraRootCA
}

func (d *DiscoveryValues) GetKeepaliveMaxServerConnectionAge() string {
	if d == nil || d.KeepaliveMaxServerConnectionAge == nil {
		return ""
	}
	return *d.KeepaliveMaxServerConnectionAge
}

func (d *DiscoveryValues) GetMemory() *DiscoveryValuesMemory {
	if d == nil {
		return nil
	}
	return d.Memory
}

func (d *DiscoveryValues) GetMeshConfig() *DiscoveryValuesMeshConfig {
	if d == nil {
		return nil
	}
	return d.MeshConfig
}

func (d *DiscoveryValues) GetNodeSelector() map[string]string {
	if d == nil {
		return nil
	}
	return d.NodeSelector
}

func (d *DiscoveryValues) GetOwnerName() string {
	if d == nil || d.OwnerName == nil {
		return ""
	}
	return *d.OwnerName
}

func (d *DiscoveryValues) GetPdb() *DiscoveryValuesPdb {
	if d == nil {
		return nil
	}
	return d.Pdb
}

func (d *DiscoveryValues) GetPlatform() string {
	if d == nil || d.Platform == nil {
		return ""
	}
	return *d.Platform
}

func (d *DiscoveryValues) GetPodAnnotations() map[string]string {
	if d == nil {
		return nil
	}
	return d.PodAnnotations
}

func (d *DiscoveryValues) GetPodLabels() map[string]string {
	if d == nil {
		return nil
	}
	return d.PodLabels
}

func (d *DiscoveryValues) GetProfile() string {
	if d == nil || d.Profile == nil {
		return ""
	}
	return *d.Profile
}

func (d *DiscoveryValues) GetReplicaCount() int {
	if d == nil || d.ReplicaCount == nil {
		return 0
	}
	return *d.ReplicaCount
}

func (d *DiscoveryValues) GetResources() *DiscoveryValuesResources {
	if d == nil {
		return nil
	}
	return d.Resources
}

func (d *DiscoveryValues) GetRevision() string {
	if d == nil || d.Revision == nil {
		return ""
	}
	return *d.Revision
}

func (d *DiscoveryValues) GetRevisionTags() []string {
	if d == nil {
		return nil
	}
	return d.RevisionTags
}

func (d *DiscoveryValues) GetRollingMaxSurge() *IntOrString {
	if d == nil {
		return nil
	}
	return d.RollingMaxSurge
}

func (d *DiscoveryValues) GetRollingMaxUnavailable() *IntOrString {
	if d == nil {
		return nil
	}
	return d.RollingMaxUnavailable
}

func (d *DiscoveryValues) GetSeccompProfile() *v1.SeccompProfile {
	if d == nil {
		return nil
	}
	return d.SeccompProfile
}

func (d *DiscoveryValues) GetServiceAccountAnnotations() map[string]string {
	if d == nil {
		return nil
	}
	return d.ServiceAccountAnnotations
}

func (d *DiscoveryValues) GetServiceAnnotations() map[string]string {
	if d == nil {
		return nil
	}
	return d.ServiceAnnotations
}

func (d *DiscoveryValues) GetSidecarInjectorWebhook() *DiscoveryValuesSidecarInjectorWebhook {
	if d == nil {
		return nil
	}
	return d.SidecarInjectorWebhook
}

func (d *DiscoveryValues) GetSidecarInjectorWebhookAnnotations() map[string]any {
	if d == nil {
		return nil
	}
	return d.SidecarInjectorWebhookAnnotations
}

func (d *DiscoveryValues) GetTag() any {
	if d == nil {
		return nil
	}
	return d.Tag
}

func (d *DiscoveryValues) GetTaint() *DiscoveryValuesTaint {
	if d == nil {
		return nil
	}
	return d.Taint
}

func (d *DiscoveryValues) GetTelemetry() *ValuesTelemetry {
	if d == nil {
		return nil
	}
	return d.Telemetry
}

func (d *DiscoveryValues) GetTolerations() []v1.Toleration {
	if d == nil {
		return nil
	}
	return d.Tolerations
}

func (d *DiscoveryValues) GetTopologySpreadConstraints() []v1.TopologySpreadConstraint {
	if d == nil {
		return nil
	}
	return d.TopologySpreadConstraints
}

func (d *DiscoveryValues) GetTraceSampling() float64 {
	if d == nil || d.TraceSampling == nil {
		return 0
	}
	return *d.TraceSampling
}

func (d *DiscoveryValues) GetTrustedZtunnelName() string {
	if d == nil || d.TrustedZtunnelName == nil {
		return ""
	}
	return *d.TrustedZtunnelName
}

func (d *DiscoveryValues) GetTrustedZtunnelNamespace() string {
	if d == nil || d.TrustedZtunnelNamespace == nil {
		return ""
	}
	return *d.TrustedZtunnelNamespace
}

func (d *DiscoveryValues) GetVariant() string {
	if d == nil || d.Variant == nil {
		return ""
	}
	return *d.Variant
}

func (d *DiscoveryValues) GetVolumeMounts() []v1.VolumeMount {
	if d == nil {
		return nil
	}
	return d.VolumeMounts
}

func (d *DiscoveryValues) GetVolumes() []v1.Volume {
	if d == nil {
		return nil
	}
	return d.Volumes
}

func (e *EgressGatewayConfig) GetAutoscaleEnabled() bool {
	if e == nil || e.AutoscaleEnabled == nil {
		return false
	}
	return *e.AutoscaleEnabled
}

func (e *EgressGatewayConfig) GetAutoscaleMax() int {
	if e == nil {
		return 0
	}
	return e.AutoscaleMax
}

func (e *EgressGatewayConfig) GetAutoscaleMin() int {
	if e == nil {
		return 0
	}
	return e.AutoscaleMin
}

func (e *EgressGatewayConfig) GetMemory() *TargetUtilizationConfig {
	if e == nil {
		return nil
	}
	return e.Memory
}

func (e *EgressGatewayConfig) GetCpu() *TargetUtilizationConfig {
	if e == nil {
		return nil
	}
	return e.Cpu
}

func (e *EgressGatewayConfig) GetCustomService() bool {
	if e == nil || e.CustomService == nil {
		return false
	}
	return *e.CustomService
}

func (e *EgressGatewayConfig) GetEnabled() bool {
	if e == nil || e.Enabled == nil {
		return false
	}
	return *e.Enabled
}

func (e *EgressGatewayConfig) GetEnv() map[string]any {
	if e == nil {
		return nil
	}
	return e.Env
}

func (e *EgressGatewayConfig) GetLabels() map[string]string {
	if e == nil {
		return nil
	}
	return e.Labels
}

func (e *EgressGatewayConfig) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

func (e *EgressGatewayConfig) GetNodeSelector() map[string]string {
	if e == nil {
		return nil
	}
	return e.NodeSelector
}

func (e *EgressGatewayConfig) GetPodAnnotations() map[string]string {
	if e == nil {
		return nil
	}
	return e.PodAnnotations
}

func (e *EgressGatewayConfig) GetPodAntiAffinityLabelSelector() []map[string]any {
	if e == nil {
		return nil
	}
	return e.PodAntiAffinityLabelSelector
}

func (e *EgressGatewayConfig) GetPodAntiAffinityTermLabelSelector() []map[string]any {
	if e == nil {
		return nil
	}
	return e.PodAntiAffinityTermLabelSelector
}

func (e *EgressGatewayConfig) GetPorts() []PortsConfig {
	if e == nil {
		return nil
	}
	return e.Ports
}

func (e *EgressGatewayConfig) GetResources() *Resources {
	if e == nil {
		return nil
	}
	return e.Resources
}

func (e *EgressGatewayConfig) GetSecretVolumes() []SecretVolume {
	if e == nil {
		return nil
	}
	return e.SecretVolumes
}

func (e *EgressGatewayConfig) GetServiceAnnotations() map[string]string {
	if e == nil {
		return nil
	}
	return e.ServiceAnnotations
}

func (e *EgressGatewayConfig) GetType() string {
	if e == nil {
		return ""
	}
	return e.Type
}

func (e *EgressGatewayConfig) GetTolerations() []v1.Toleration {
	if e == nil {
		return nil
	}
	return e.Tolerations
}

func (e *EgressGatewayConfig) GetRollingMaxSurge() *IntOrString {
	if e == nil {
		return nil
	}
	return e.RollingMaxSurge
}

func (e *EgressGatewayConfig) GetRollingMaxUnavailable() *IntOrString {
	if e == nil {
		return nil
	}
	return e.RollingMaxUnavailable
}

func (e *EgressGatewayConfig) GetConfigVolumes() []v1.Volume {
	if e == nil {
		return nil
	}
	return e.ConfigVolumes
}

func (e *EgressGatewayConfig) GetAdditionalContainers() []v1.Container {
	if e == nil {
		return nil
	}
	return e.AdditionalContainers
}

func (e *EgressGatewayConfig) GetRunAsRoot() bool {
	if e == nil || e.RunAsRoot == nil {
		return false
	}
	return *e.RunAsRoot
}

func (e *EgressGatewayConfig) GetInjectionTemplate() string {
	if e == nil {
		return ""
	}
	return e.InjectionTemplate
}

func (e *EgressGatewayConfig) GetServiceAccount() *ServiceAccount {
	if e == nil {
		return nil
	}
	return e.ServiceAccount
}

func (e *EgressGatewayConfig) GetIpFamilies() []string {
	if e == nil {
		return nil
	}
	return e.IpFamilies
}

func (e *EgressGatewayConfig) GetIpFamilyPolicy() string {
	if e == nil {
		return ""
	}
	return e.IpFamilyPolicy
}

func (g *GatewaysConfig) GetIstioEgressgateway() *EgressGatewayConfig {
	if g == nil {
		return nil
	}
	return g.IstioEgressgateway
}

func (g *GatewaysConfig) GetEnabled() bool {
	if g == nil || g.Enabled == nil {
		return false
	}
	return *g.Enabled
}

func (g *GatewaysConfig) GetIstioIngressgateway() *IngressGatewayConfig {
	if g == nil {
		return nil
	}
	return g.IstioIngressgateway
}

func (g *GatewaysConfig) GetSecurityContext() *v1.PodSecurityContext {
	if g == nil {
		return nil
	}
	return g.SecurityContext
}

func (g *GatewaysConfig) GetSeccompProfile() *v1.SeccompProfile {
	if g == nil {
		return nil
	}
	return g.SeccompProfile
}

func (i *IngressGatewayConfig) GetAutoscaleEnabled() bool {
	if i == nil || i.AutoscaleEnabled == nil {
		return false
	}
	return *i.AutoscaleEnabled
}

func (i *IngressGatewayConfig) GetAutoscaleMax() int {
	if i == nil {
		return 0
	}
	return i.AutoscaleMax
}

func (i *IngressGatewayConfig) GetAutoscaleMin() int {
	if i == nil {
		return 0
	}
	return i.AutoscaleMin
}

func (i *IngressGatewayConfig) GetMemory() *TargetUtilizationConfig {
	if i == nil {
		return nil
	}
	return i.Memory
}

func (i *IngressGatewayConfig) GetCpu() *TargetUtilizationConfig {
	if i == nil {
		return nil
	}
	return i.Cpu
}

func (i *IngressGatewayConfig) GetCustomService() bool {
	if i == nil || i.CustomService == nil {
		return false
	}
	return *i.CustomService
}

func (i *IngressGatewayConfig) GetEnabled() bool {
	if i == nil || i.Enabled == nil {
		return false
	}
	return *i.Enabled
}

func (i *IngressGatewayConfig) GetEnv() map[string]any {
	if i == nil {
		return nil
	}
	return i.Env
}

func (i *IngressGatewayConfig) GetLabels() map[string]string {
	if i == nil {
		return nil
	}
	return i.Labels
}

func (i *IngressGatewayConfig) GetLoadBalancerIP() string {
	if i == nil {
		return ""
	}
	return i.LoadBalancerIP
}

func (i *IngressGatewayConfig) GetLoadBalancerSourceRanges() []string {
	if i == nil {
		return nil
	}
	return i.LoadBalancerSourceRanges
}

func (i *IngressGatewayConfig) GetName() string {
	if i == nil {
		return ""
	}
	return i.Name
}

func (i *IngressGatewayConfig) GetNodeSelector() map[string]string {
	if i == nil {
		return nil
	}
	return i.NodeSelector
}

func (i *IngressGatewayConfig) GetPodAnnotations() map[string]string {
	if i == nil {
		return nil
	}
	return i.PodAnnotations
}

func (i *IngressGatewayConfig) GetPodAntiAffinityLabelSelector() []map[string]any {
	if i == nil {
		return nil
	}
	return i.PodAntiAffinityLabelSelector
}

func (i *IngressGatewayConfig) GetPodAntiAffinityTermLabelSelector() []map[string]any {
	if i == nil {
		return nil
	}
	return i.PodAntiAffinityTermLabelSelector
}

func (i *IngressGatewayConfig) GetPorts() []PortsConfig {
	if i == nil {
		return nil
	}
	return i.Ports
}

func (i *IngressGatewayConfig) GetReplicaCount() int {
	if i == nil {
		return 0
	}
	return i.ReplicaCount
}

func (i *IngressGatewayConfig) GetResources() *Resources {
	if i == nil {
		return nil
	}
	return i.Resources
}

func (i *IngressGatewayConfig) GetSecretVolumes() []SecretVolume {
	if i == nil {
		return nil
	}
	return i.SecretVolumes
}

func (i *IngressGatewayConfig) GetServiceAnnotations() map[string]string {
	if i == nil {
		return nil
	}
	return i.ServiceAnnotations
}

func (i *IngressGatewayConfig) GetType() string {
	if i == nil {
		return ""
	}
	return i.Type
}

func (i *IngressGatewayConfig) GetRollingMaxSurge() *IntOrString {
	if i == nil {
		return nil
	}
	return i.RollingMaxSurge
}

func (i *IngressGatewayConfig) GetRollingMaxUnavailable() *IntOrString {
	if i == nil {
		return nil
	}
	return i.RollingMaxUnavailable
}

func (i *IngressGatewayConfig) GetExternalTrafficPolicy() string {
	if i == nil {
		return ""
	}
	return i.ExternalTrafficPolicy
}

func (i *IngressGatewayConfig) GetTolerations() []v1.Toleration {
	if i == nil {
		return nil
	}
	return i.Tolerations
}

func (i *IngressGatewayConfig) GetIngressPorts() []map[string]any {
	if i == nil {
		return nil
	}
	return i.IngressPorts
}

func (i *IngressGatewayConfig) GetAdditionalContainers() []v1.Container {
	if i == nil {
		return nil
	}
	return i.AdditionalContainers
}

func (i *IngressGatewayConfig) GetConfigVolumes() []v1.Volume {
	if i == nil {
		return nil
	}
	return i.ConfigVolumes
}

func (i *IngressGatewayConfig) GetRunAsRoot() bool {
	if i == nil || i.RunAsRoot == nil {
		return false
	}
	return *i.RunAsRoot
}

func (i *IngressGatewayConfig) GetInjectionTemplate() string {
	if i == nil {
		return ""
	}
	return i.InjectionTemplate
}

func (i *IngressGatewayConfig) GetServiceAccount() *ServiceAccount {
	if i == nil {
		return nil
	}
	return i.ServiceAccount
}

func (i *IngressGatewayConfig) GetIpFamilies() []string {
	if i == nil {
		return nil
	}
	return i.IpFamilies
}

func (i *IngressGatewayConfig) GetIpFamilyPolicy() string {
	if i == nil {
		return ""
	}
	return i.IpFamilyPolicy
}

func (i *IstiodRemoteConfig) GetInjectionURL() string {
	if i == nil {
		return ""
	}
	return i.InjectionURL
}

func (i *IstiodRemoteConfig) GetInjectionPath() string {
	if i == nil {
		return ""
	}
	return i.InjectionPath
}

func (i *IstiodRemoteConfig) GetInjectionCABundle() string {
	if i == nil {
		return ""
	}
	return i.InjectionCABundle
}

func (i *IstiodRemoteConfig) GetEnabled() bool {
	if i == nil || i.Enabled == nil {
		return false
	}
	return *i.Enabled
}

func (i *IstiodRemoteConfig) GetEnabledLocalInjectorIstiod() bool {
	if i == nil || i.EnabledLocalInjectorIstiod == nil {
		return false
	}
	return *i.EnabledLocalInjectorIstiod
}

func (o *OutboundTrafficPolicyConfig) GetMode() string {
	if o == nil {
		return ""
	}
	return o.Mode
}

func (p *PilotIngressConfig) GetIngressService() string {
	if p == nil {
		return ""
	}
	return p.IngressService
}

func (p *PilotIngressConfig) GetIngressControllerMode() string {
	if p == nil {
		return ""
	}
	return p.IngressControllerMode
}

func (p *PilotIngressConfig) GetIngressClass() string {
	if p == nil {
		return ""
	}
	return p.IngressClass
}

func (p *PilotPolicyConfig) GetEnabled() bool {
	if p == nil || p.Enabled == nil {
		return false
	}
	return *p.Enabled
}

func (p *PortsConfig) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PortsConfig) GetPort() int {
	if p == nil {
		return 0
	}
	return p.Port
}

func (p *PortsConfig) GetNodePort() int {
	if p == nil {
		return 0
	}
	return p.NodePort
}

func (p *PortsConfig) GetTargetPort() int {
	if p == nil {
		return 0
	}
	return p.TargetPort
}

func (p *PortsConfig) GetProtocol() string {
	if p == nil {
		return ""
	}
	return p.Protocol
}

func (s *SecretVolume) GetMountPath() string {
	if s == nil {
		return ""
	}
	return s.MountPath
}

func (s *SecretVolume) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SecretVolume) GetSecretName() string {
	if s == nil {
		return ""
	}
	return s.SecretName
}

func (s *ServiceAccount) GetAnnotations() map[string]any {
	if s == nil {
		return nil
	}
	return s.Annotations
}

func (s *SidecarInjectorConfig) GetEnableNamespacesByDefault() bool {
	if s == nil || s.EnableNamespacesByDefault == nil {
		return false
	}
	return *s.EnableNamespacesByDefault
}

func (s *SidecarInjectorConfig) GetReinvocationPolicy() string {
	if s == nil {
		return ""
	}
	return s.ReinvocationPolicy
}

func (s *SidecarInjectorConfig) GetNeverInjectSelector() []map[string]any {
	if s == nil {
		return nil
	}
	return s.NeverInjectSelector
}

func (s *SidecarInjectorConfig) GetAlwaysInjectSelector() []map[string]any {
	if s == nil {
		return nil
	}
	return s.AlwaysInjectSelector
}

func (s *SidecarInjectorConfig) GetRewriteAppHTTPProbe() bool {
	if s == nil || s.RewriteAppHTTPProbe == nil {
		return false
	}
	return *s.RewriteAppHTTPProbe
}

func (s *SidecarInjectorConfig) GetInjectedAnnotations() map[string]any {
	if s == nil {
		return nil
	}
	return s.InjectedAnnotations
}

func (s *SidecarInjectorConfig) GetInjectionURL() string {
	if s == nil {
		return ""
	}
	return s.InjectionURL
}

func (s *SidecarInjectorConfig) GetTemplates() map[string]any {
	if s == nil {
		return nil
	}
	return s.Templates
}

func (s *SidecarInjectorConfig) GetDefaultTemplates() []string {
	if s == nil {
		return nil
	}
	return s.DefaultTemplates
}

func (t *TargetUtilizationConfig) GetTargetAverageUtilization() int {
	if t == nil {
		return 0
	}
	return t.TargetAverageUtilization
}

func (t *TracerConfig) GetDatadog() *TracerDatadogConfig {
	if t == nil {
		return nil
	}
	return t.Datadog
}

func (t *TracerConfig) GetLightstep() *TracerLightStepConfig {
	if t == nil {
		return nil
	}
	return t.Lightstep
}

func (t *TracerConfig) GetZipkin() *TracerZipkinConfig {
	if t == nil {
		return nil
	}
	return t.Zipkin
}

func (t *TracerConfig) GetStackdriver() *TracerStackdriverConfig {
	if t == nil {
		return nil
	}
	return t.Stackdriver
}

func (t *TracerDatadogConfig) GetAddress() string {
	if t == nil {
		return ""
	}
	return t.Address
}

func (t *TracerLightStepConfig) GetAddress() string {
	if t == nil {
		return ""
	}
	return t.Address
}

func (t *TracerLightStepConfig) GetAccessToken() string {
	if t == nil {
		return ""
	}
	return t.AccessToken
}

func (t *TracerStackdriverConfig) GetDebug() bool {
	if t == nil || t.Debug == nil {
		return false
	}
	return *t.Debug
}

func (t *TracerStackdriverConfig) GetMaxNumberOfAttributes() int {
	if t == nil {
		return 0
	}
	return t.MaxNumberOfAttributes
}

func (t *TracerStackdriverConfig) GetMaxNumberOfAnnotations() int {
	if t == nil {
		return 0
	}
	return t.MaxNumberOfAnnotations
}

func (t *TracerStackdriverConfig) GetMaxNumberOfMessageEvents() int {
	if t == nil {
		return 0
	}
	return t.MaxNumberOfMessageEvents
}

func (t *TracerZipkinConfig) GetAddress() string {
	if t == nil {
		return ""
	}
	return t.Address
}

func (v *ValuesExperimental) GetStableValidationPolicy() bool {
	if v == nil || v.StableValidationPolicy == nil {
		return false
	}
	return *v.StableValidationPolicy
}

func (v *ValuesTelemetry) GetEnabled() bool {
	if v == nil || v.Enabled == nil {
		return false
	}
	return *v.Enabled
}

func (v *ValuesTelemetry) GetV2() *ValuesTelemetryV2 {
	if v == nil {
		return nil
	}
	return v.V2
}

func (v *ValuesTelemetryV2) GetEnabled() bool {
	if v == nil || v.Enabled == nil {
		return false
	}
	return *v.Enabled
}

func (v *ValuesTelemetryV2) GetPrometheus() *ValuesTelemetryV2Prometheus {
	if v == nil {
		return nil
	}
	return v.Prometheus
}

func (v *ValuesTelemetryV2) GetStackdriver() *ValuesTelemetryV2Stackdriver {
	if v == nil {
		return nil
	}
	return v.Stackdriver
}

func (v *ValuesTelemetryV2Prometheus) GetEnabled() bool {
	if v == nil || v.Enabled == nil {
		return false
	}
	return *v.Enabled
}

func (v *ValuesTelemetryV2Stackdriver) GetEnabled() bool {
	if v == nil || v.Enabled == nil {
		return false
	}
	return *v.Enabled
}
